#!/bin/sh

runvifm()
{
    if [ -z "$1"  ]; then
        vifm "$PWD" "$HOME" 
    else
        vifm "$1" "$HOME" 
    fi
}

if [ -z "$(command -v vifm)" ]; then
	printf "vifm isn't installed on your system!\n"
	exit 1
elif [ -z "$(command -v ueberzug)" ]; then
	exec vifm "$@"
else
	cleanup() {
		exec 3>&-
	    rm "$FIFO_UEBERZUG"
	}
    CACHEDIR="${XDG_CACHE_HOME:-$HOME/.cache}/vifm"
	[ ! -d "$CACHEDIR" ] && mkdir -p "$CACHEDIR"
	export FIFO_UEBERZUG="$CACHEDIR/ueberzug-${$}"
	mkfifo "$FIFO_UEBERZUG"
	ueberzug layer -s <"$FIFO_UEBERZUG" -p json &
	exec 3>"$FIFO_UEBERZUG"
	trap cleanup EXIT
	runvifm "$@" 
	# runvifm "$@" 3>&-
	# vifm "$@" 3>&-
	vifmimg clear
fi

