#!/bin/sh

if [ -z "$(command -v vifm)" ]; then
	printf "vifm isn't installed on your system!\n"
	exit 1
elif [ -z "$(command -v ueberzug)" ]; then
	exec vifm "$@"
else
	cleanup() {
		exec 3>&-
	    rm "$FIFO_UEBERZUG"
	}
    CACHEDIR="${XDG_CACHE_HOME:-$HOME/.cache}/vifm"
	[ ! -d "$CACHEDIR" ] && mkdir -p "$CACHEDIR"
	export FIFO_UEBERZUG="$CACHEDIR/ueberzug-${$}"
	mkfifo "$FIFO_UEBERZUG"
	ueberzug layer -s <"$FIFO_UEBERZUG" -p json &
	exec 3>"$FIFO_UEBERZUG"
	trap cleanup EXIT
	vifm "$@" 3>&-
	vifmimg clear
fi

# go to cwd if vifm is closed
if [ -z "$1"  ]; then
    vifm "$PWD" "$HOME"  > /dev/null 2>&1
else
    vifm "$1" "$HOME" > /dev/null 2>&1
fi
